"""create_all_21_tables

Revision ID: a6c57a4fd8f6
Revises: f584559a44ea
Create Date: 2026-05-31 06:55:45.611384
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'a6c57a4fd8f6'
down_revision: Union[str, None] = 'f584559a44ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('code'), table_name='coo')
    op.drop_table('coo')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('credits', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'coo', ['code'], unique=True)
    # ### end Alembic commands ###
