"""create_all_20_tables

Revision ID: f584559a44ea
Revises: 
Create Date: 2026-05-31 06:48:15.746046
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f584559a44ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    # ### end Alembic commands ###
